// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEnO9TnlaUfqDgXwvwvIlvqdLF2RDTo1Q',
    appId: '1:333035118591:web:b0b05b3ff4ee63648791ca',
    messagingSenderId: '333035118591',
    projectId: 'spook-a-chess',
    authDomain: 'spook-a-chess.firebaseapp.com',
    storageBucket: 'spook-a-chess.firebasestorage.app',
    measurementId: 'G-QNN98KP7XY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkkb_c8VraGOC7Xk3DNl8GG3svqvSgJgc',
    appId: '1:333035118591:android:7bb29e0b41fbe87b8791ca',
    messagingSenderId: '333035118591',
    projectId: 'spook-a-chess',
    storageBucket: 'spook-a-chess.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFyacbmycM82__P1DeMUygVRccXN78Cds',
    appId: '1:333035118591:ios:6599563bf3a6d8be8791ca',
    messagingSenderId: '333035118591',
    projectId: 'spook-a-chess',
    storageBucket: 'spook-a-chess.firebasestorage.app',
    iosBundleId: 'com.example.superChess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEnO9TnlaUfqDgXwvwvIlvqdLF2RDTo1Q',
    appId: '1:333035118591:web:4985841bf6dbc19c8791ca',
    messagingSenderId: '333035118591',
    projectId: 'spook-a-chess',
    authDomain: 'spook-a-chess.firebaseapp.com',
    storageBucket: 'spook-a-chess.firebasestorage.app',
    measurementId: 'G-8DG369M3BD',
  );
}
